name: MuleSoft CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and Package Application
        run: mvn clean package -e -X

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mulesoft-app
          path: target/*.jar

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: mulesoft-app

      - name: Deploy to Anypoint Platform (Development)
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn org.mule.tools.maven:mule-maven-plugin:3.8.0:deploy \
            -Dmule.artifact=$artifactName \
            -Danypoint.username=$ANYPOINT_USERNAME \
            -Danypoint.password=$ANYPOINT_PASSWORD \
            -Danypoint.environment=dev -e -X

  deploy-test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: mulesoft-app

      - name: Deploy to Anypoint Platform (Test)
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn org.mule.tools.maven:mule-maven-plugin:3.8.0:deploy \
            -Dmule.artifact=$artifactName \
            -Danypoint.username=$ANYPOINT_USERNAME \
            -Danypoint.password=$ANYPOINT_PASSWORD \
            -Danypoint.environment=test -e -X

  deploy-production:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: mulesoft-app

      - name: Deploy to Anypoint Platform (Production)
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn org.mule.tools.maven:mule-maven-plugin:3.8.0:deploy \
            -Dmule.artifact=$artifactName \
            -Danypoint.username=$ANYPOINT_USERNAME \
            -Danypoint.password=$ANYPOINT_PASSWORD \
            -Danypoint.environment=prod -e -X
