name: MuleSoft CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   


      - name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-   


      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version:   
 1.8 

      - name: Configure Maven settings for Anypoint Exchange
        uses: whelk-io/maven-settings-xml-action@v16
        with:
          servers: |
            [
              {
                "id": "anypoint-exchange-v3",
                "username": "${{ secrets.ANYPOINT_USERNAME }}",
                "password": "${{ secrets.ANYPOINT_PASSWORD }}"
              }
            ]
          repositories: |
            [
              {
                "id": "anypoint-exchange-v3",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven",
                "releases": { "enabled": "true" },
                "snapshots": { "enabled": "true" }
              }
            ]

      - name: Build and Package Application
        run: mvn clean package -e -X

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mulesoft-app
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3   

        with:
          name:   
 mulesoft-app

      - name: Deploy to Anypoint Platform
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          ANYPOINT_ENVIRONMENT: ${{ secrets.ANYPOINT_ENVIRONMENT }} 
        run: |
          artifactName=$(ls target/*.jar | head -1)
          mvn org.mule.tools.maven:mule-maven-plugin:3.8.2:deploy \
            -Dmule.artifact=$artifactName \
            -Danypoint.username=$ANYPOINT_USERNAME \
            -Danypoint.password=$ANYPOINT_PASSWORD \
            -Danypoint.environment=$ANYPOINT_ENVIRONMENT
